# Use an official, lightweight Python image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file first to leverage Docker's caching
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy your application code into the container
COPY ./app /app/app


# Expose the port the app runs on
EXPOSE 8080


CMD ["uvicorn", "app.fast_api:app", "--host", "0.0.0.0", "--port", "8080"]